
create table if not exists public.toners (
  id bigint generated by default as identity primary key,
  toner_model text not null,
  alternate_code text,
  printers text[] not null default '{}',
  selling_rate numeric(12,2) not null default 0,
  stock integer not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.toners enable row level security;

drop policy if exists "Public can view active toners" on public.toners;
create policy "Public can view active toners"
on public.toners for select
to anon, authenticated
using (active = true);

drop policy if exists "Authenticated users can insert toners" on public.toners;
create policy "Authenticated users can insert toners"
on public.toners for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update toners" on public.toners;
create policy "Authenticated users can update toners"
on public.toners for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete toners" on public.toners;
create policy "Authenticated users can delete toners"
on public.toners for delete
to authenticated
using (true);

insert into public.toners
(toner_model, alternate_code, printers, selling_rate, stock)
values
('NPG-51','GPR-35 / C-EXV33',ARRAY['Canon iR 2520','Canon iR 2525','Canon iR 2530'],0,0),
('NPG-87','C-EXV63',ARRAY['Canon iR 2725','Canon iR 2730','Canon iR 2735','Canon iR 2745'],0,0),
('NPG-90','C-EXV67',ARRAY['Canon iR 2925','Canon iR 2930','Canon iR 2935','Canon iR 2945'],0,0),
('G84','C-EXV59',ARRAY['Canon iR 2625','Canon iR 2630','Canon iR 2635','Canon iR 2645'],0,0),
('G-73','GPR-57 / C-EXV53',ARRAY['Canon imageRUNNER ADVANCE 4525','Canon imageRUNNER ADVANCE 4535','Canon imageRUNNER ADVANCE 4545','Canon imageRUNNER ADVANCE 4551','Canon imageRUNNER ADVANCE DX 4725i','Canon imageRUNNER ADVANCE DX 4735i','Canon imageRUNNER ADVANCE DX 4745i','Canon imageRUNNER ADVANCE DX 4751i'],0,0),
('G-59','NPG-59 / C-EXV42',ARRAY['Canon iR 2002','Canon iR 2002N','Canon iR 2004','Canon iR 2004N','Canon iR 2006N','Canon iR 2202','Canon iR 2204','Canon iR 2206'],0,0);
